spring.application.name=springboot
server.port=8080
spring.mvc.converters.preferred-json-mapper=jackson
spring.jackson.mapper.ACCEPT_CASE_INSENSITIVE_PROPERTIES=true
spring.thymeleaf.cache=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=weplmanager2024@gmail.com
spring.mail.password=qpjhpvgggjypxytt
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
