spring.application.name=springboot
server.port=8080
spring.mvc.converters.preferred-json-mapper=jackson
spring.jackson.mapper.ACCEPT_CASE_INSENSITIVE_PROPERTIES=true
spring.thymeleaf.cache=false

google.api.key=AIzaSyBpYHuPzcz63P3hz-xSUNm75qIYmMur9sc
foursquare.api.key=fsq3uJb5W14pqg1wFsyGryVzpaJeut5pRRfy0PnZunTmhRI=
gpt.api.key=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
weather.api.key=u6UNNYjDKmjjkqebR3K1bkhOm1QUZgZtDJBQEP0fUrFZR0LNCsdqWLtuAl9K%2FZ75kuUHKYTri5BTXwpMpX6iVg%3D%3D

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=weplmanager2024@gmail.com
spring.mail.password=qpjhpvgggjypxytt
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
